kind: ConfigMap
apiVersion: v1
metadata:
  name: metal3-config
  namespace: openshift-machine-api
data:
  http_port: "6180"
  provisioning_interface: "ens3"
  provisioning_ip: "172.22.0.3/24"
  dhcp_range: "172.22.0.10,172.22.0.100"
  deploy_kernel_url: "http://172.22.0.3:6180/images/ironic-python-agent.kernel"
  deploy_ramdisk_url: "http://172.22.0.3:6180/images/ironic-python-agent.initramfs"
  ironic_endpoint: "http://172.22.0.3:6385/v1/"
  ironic_inspector_endpoint: "http://172.22.0.3:5050/v1/"
  cache_url: "http://[fd35:919d:4042:2::1155]/images"
  rhcos_image_url: "http://172.22.0.1/images/rhcos-43.81.202001142154.0-openstack.x86_64.qcow2.gz?sha256=2da72a1eaee005458014cfbab93f77c459b8c63ff110f0d4cbf4c13e7001de68"
